# The MIT License (MIT)
#
# Copyright (c) 2017-2025 Yegor Bugayenko
#
# Permission is hereby granted, free of charge,  to any person obtaining
# a copy  of  this  software  and  associated  documentation files  (the
# "Software"),  to deal in the Software  without restriction,  including
# without limitation the rights to use,  copy,  modify,  merge, publish,
# distribute,  sublicense,  and/or sell  copies of the Software,  and to
# permit persons to whom the Software is furnished to do so,  subject to
# the  following  conditions:   the  above  copyright  notice  and  this
# permission notice  shall  be  included  in  all copies or  substantial
# portions of the Software.  The software is provided  "as is",  without
# warranty of any kind, express or implied, including but not limited to
# the warranties  of merchantability,  fitness for  a particular purpose
# and non-infringement.  In  no  event shall  the  authors  or copyright
# holders be liable for any claim,  damages or other liability,  whether
# in an action of contract,  tort or otherwise,  arising from, out of or
# in connection with the software or  the  use  or other dealings in the
# software.
---
# yamllint disable rule:line-length
name: mvn
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
        java: [11, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: java -version
      - run: mvn -version
      - run: mvn --errors --batch-mode clean install -Pqulice
